ant-design/ant-design-mini

- package.json
- src/mixins/controlled.ts
and format the content use prettier
> chore: update invalid typing

- config/config.ts
发现模拟器初始化时有明显闪烁（从默认模拟器到 Lyra），先用 CSS 绕过该问题，等 Lyra 容器复用的能力上线后再移除
> docs: workaround for simulator flicker problem

- package.json
- src/Collapse/props.d.ts
- src/NoticeBar/index.ts
- src/SwipeAction/index.ts
- src/Tabs/index.ts
- src/VTabs/index.ts
- src/_base/index.d.ts
- tsconfig.json
目前 my 仅提供了 api function 的导出，在没有确认最终形态前，先不要使用内部的 interface，因为会一直变
> fix(types): remove invalid use for my

- scripts/docs/src/markdown/const/index.ts
- scripts/docs/src/markdown/index.ts
- scripts/docs/src/parser/axml/index.ts
- scripts/docs/src/parser/less/index.ts
- scripts/docs/src/parser/ts/index.ts
- scripts/docs/src/utils/index.ts
fix variable naming 'conent' to 'content'
> fix(scripts): fix variable naming

- src/Selector/index.axml
- src/Selector/index.sjs
chore(selector): fix xml condition determination issues to match 'vx'
> chore(selector): fix xml condition determination issues to match 'vx'

- plugin/index.ts
- plugin/render.js
> feat(docs): adjust demo source file sort

- src/CheckboxGroup/index.axml
> fix: fix CheckboxGroup header prop

- src/RadioGroup/RadioItem/index.ts
- src/RadioGroup/RadioItem/props.d.ts
- src/RadioGroup/index.md
> fix(RadioGroup): fix checked bug

- config/config.ts
- demo/pages/Icon/index.acss
- demo/pages/Icon/index.axml
- demo/pages/Icon/index.js
feat(icon):  支持官网 demo 中点击对应 icon 复制对应 type，同时在 dev 中 IDE 中也支持复制。
> feat(icon): click support to copy icon Type

- src/Collapse/CollapseItem/index.ts
- src/Collapse/CollapseItem/props.d.ts
- src/Collapse/index.md
- src/Collapse/index.ts
- src/Collapse/props.d.ts
- src/Filter/FilterItem/index.ts
- src/Filter/FilterItem/props.d.ts
- src/Filter/index.md
- src/Filter/index.ts
- src/Filter/props.d.ts
- src/Steps/StepItem/index.ts
- src/Steps/StepItem/props.d.ts
- src/Steps/index.md
- src/Steps/index.ts
- src/Steps/props.d.ts
- src/Tabs/TabItem/index.ts
- src/Tabs/index.ts
* adjust Steps、Filter、Collapse uid to page unique
> feat: adjust Steps、Filter、Collapse uid to page unique

- plugin/render.js
> feat: update demo cdn

- demo/app.json
- demo/pages/Empty/index.acss
- demo/pages/Empty/index.axml
- demo/pages/Empty/index.js
- demo/pages/Empty/index.json
- demo/utils/constants.ts
- src/Empty/index.axml
- src/Empty/index.json
- src/Empty/index.less
- src/Empty/index.md
- src/Empty/index.ts
- src/Empty/props.d.ts
- src/Empty/props.js
- src/Empty/variable.less
feat(empty): add empty compoennt
> feat(empty): add empty compoennt

- demo/app.json
- demo/pages/Checklist/index.acss
- demo/pages/Checklist/index.axml
- demo/pages/Checklist/index.js
- demo/pages/Checklist/index.json
- demo/utils/constants.ts
- src/Checklist/ChecklistItem/index.axml
- src/Checklist/ChecklistItem/index.json
- src/Checklist/ChecklistItem/index.less
- src/Checklist/ChecklistItem/index.ts
- src/Checklist/ChecklistItem/props.d.ts
- src/Checklist/ChecklistItem/props.js
- src/Checklist/index.axml
- src/Checklist/index.json
- src/Checklist/index.less
- src/Checklist/index.md
- src/Checklist/index.ts
- src/Checklist/props.d.ts
- src/Checklist/props.js
- src/Checklist/variable.less
> feat(Checklist): new checklist component

- src/List/ListItem/index.sjs
- src/Stepper/index.axml
- 移除 stepper 测试代码
- 移除 listItem sjs 测试代码
> chore(stepper): remove useless code

- src/Tabs/index.axml
- src/Tabs/index.md
- src/Tabs/props.d.ts
- src/Tabs/props.js
> feat(Tabs): add attributes for swiper

- src/Icon/index.less
* 修复 Icon 在插件场景下css color优先级被覆盖问题
* issues #72
> fix(Icon): fix color style used in plugin

- src/Picker/index.ts
修复 https://github.com/ant-design/ant-design-mini/issues/89
> chore(Picker): this.dataList sync  with props.data

- config/config.ts
- demo/app.acss
- demo/components/DemoBlock/index.acss
- demo/pages/Button/index.acss
- demo/pages/Button/index.axml
1. google analytics替换友盟
2. lyra样式微调
> feat(doc): google analytics

- src/Tips/TipsItem/index.less
- src/Tips/index.axml
- src/Tips/index.less
- src/Tips/index.ts
> feat(Tips): 单行文本时关闭按钮垂直居中

- src/Tabs/index.less
> fix(Tabs): fix title style in IOS9

- src/Filter/FilterItem/index.ts
> fix(Filter): 修复 selector onChange 数据格式

- src/ActionSheet/index.md
- src/Button/index.md
- src/FloatPanel/index.md
- src/Form/index.md
- src/Icon/index.md
- src/List/index.md
- src/Loading/index.md
- src/Mask/index.md
- src/SearchBar/index.md
- src/Switch/index.md
- src/Terms/index.md
- src/VTabs/index.md
> chore: update doc

- demo/app.json
- demo/pages/ImageUpload/index.acss
- demo/pages/ImageUpload/index.axml
- demo/pages/ImageUpload/index.js
- demo/pages/ImageUpload/index.json
- demo/pages/VideoUpload/index.acss
- demo/pages/VideoUpload/index.axml
- demo/pages/VideoUpload/index.js
- demo/pages/VideoUpload/index.json
- demo/utils/constants.js
- src/ImageUpload/index.axml
- src/ImageUpload/index.json
- src/ImageUpload/index.less
- src/ImageUpload/index.md
- src/ImageUpload/index.ts
- src/ImageUpload/props.d.ts
- src/ImageUpload/props.js
- src/ImageUpload/variable.less
- src/VideoUpload/index.axml
- src/VideoUpload/index.json
- src/VideoUpload/index.less
- src/VideoUpload/index.md
- src/VideoUpload/index.ts
- src/VideoUpload/props.d.ts
- src/VideoUpload/props.js
- src/VideoUpload/variable.less
- src/_util/promisify.ts
> feat(imageVideoUpload): add imageUpload and videoUpload

- demo/pages/Selector/index.axml
- demo/pages/Selector/index.js
- src/Selector/index.json
- src/Selector/index.md
- src/Selector/index.ts
- src/Selector/props.d.ts
- src/Selector/props.js
> feat(Selector): add maxSelectedCount、minSelectedCount  prop

- demo/app.json
- demo/pages/VTabsNoScroll/index.acss
- demo/pages/VTabsNoScroll/index.axml
- demo/pages/VTabsNoScroll/index.js
- demo/pages/VTabsNoScroll/index.json
- src/VTabs/index.md
> feat(vTabs): add demo for switching content by tab click

- src/Badge/index.md
- src/Badge/props.js
> fix(Badge): fix position prop

- src/InputItem/index.md
- src/InputItem/index.ts
https://github.com/ant-design/ant-design-mini/issues/187#issue-1305637970
> Add event to input component‘event

- src/Switch/index.less
> feat(Switch): modify handleIcon box-shadow

- src/Form/FormGroup/index.axml
- src/Form/FormGroup/index.json
- src/Form/FormGroup/index.less
- src/_base/index.less
- 移除 formGroup 无用的 list 组件引用
- 统一 formGroup 格式化
> feat(formGroup): remove useless refer and format style

- src/InputItem/index.axml
- src/InputItem/index.less
> fix(inputItem): fix input care color

- demo/pages/ImageUpload/index.axml
- demo/pages/ImageUpload/index.js
- src/ImageUpload/index.md
- src/ImageUpload/index.ts
- src/ImageUpload/props.d.ts
- 图片上传组件支持不同类型的值，包括 string 、string[] 和 File[]
- 更新对应demo
> feat(imageUpload): support different value type

- src/Popup/index.axml
- src/Popup/index.less
- src/Popup/index.ts
- src/Popup/props.d.ts
> feat(Popup): add close animation

- config/config.ts
- docs/components/home.tsx
- open dumi sitemap and ssr config to implement docsearch
> feat(config): open dumi sitemap and ssr to implement docsearch

- src/Tabs/index.md
- src/Tabs/index.ts
https://github.com/ant-design/ant-design-mini/issues/221#issue-1334007790
> feat(Tabs): add event param to `onChange`

- demo/app.json
- src/NoticeBar/index.axml
- src/NoticeBar/index.less
- src/NoticeBar/index.ts
- src/NoticeBar/props.d.ts
修复NoticeBar在页面onHide再回来时滚动动画异常问题
> fix(NoticeBar): fix marquee on pageHide

- src/Tabs/index.md
- src/Tabs/props.d.ts
> docs(tabs): new stickyTop props in md

- demo/pages/Popup/index.axml
- demo/pages/Popup/index.js
- src/Popup/index.axml
- src/Popup/index.less
- src/Popup/index.md
- src/Popup/props.d.ts
- src/Popup/props.js
> feat(Popup): add  autoHeight props

- src/ImageUpload/index.ts
- src/VideoUpload/index.ts
- 兼容 imageUpload、videoUpload value为字符串的形式
> feat: compatibility value is string in uploader

- demo/pages/ImageUpload/index.axml
- src/ImageUpload/index.ts
- 修复 onBeforeUpload 同时上传多张图片时只展示最后一张图片的问题
https://github.com/ant-design/ant-design-mini/issues/255
> fix(imageUpload): fix onBeforeUpload

- src/Stepper/index.md
> chore(docs): 调整stepper type说明文档

- src/Tabs/index.axml
- src/Tabs/index.md
> feat: support badge

- src/InputItem/index.ts
> fix(inputItem): remove repeat import

- src/Grid/GridItem/index.axml
- src/Grid/GridItem/index.ts
- src/Grid/GridItem/props.d.ts
- src/Grid/index.axml
- src/Grid/index.md
- src/Grid/index.ts
- src/Grid/props.d.ts
> feat(grid): support onFirstAppear method

- demo/pages/CollapseCustom/index.axml
- src/Collapse/index.ts
fix lose controlled in collapse
> fix(collapse): fix lose controlled

- src/Rate/index.axml
- src/Rate/index.md
- src/Rate/props.d.ts
- src/Rate/props.js
props调整
1.  activeColor 参数 支持传入渐变色值。例如：activeColor="linear-gradient(rgb(197, 113, 113),rgb(128, 128, 209)"。
2. inactiveColor 参数 支持传入渐变色值。例如：activeColor="linear-gradient(rgb(197, 113, 113),rgb(128, 128, 209)"。
> Rate组件参数调整

- demo/pages/TabBar/index.js
- src/TabBar/index.axml
> fix: tabBar

- demo/pages/Divider/index.acss
- demo/pages/Divider/index.axml
- demo/pages/Divider/index.json
- src/Divider/index.axml
- src/Divider/index.less
- src/Divider/index.md
- src/Divider/props.js
- src/Divider/variable.less
- src/style/themes/color.less
- 新增暗黑模式
- borderColor、borderStyle 分别调整了 lineColor、lineType
- 新增 textClassName、textStyle、style
- 新增 lineHeight、lineWidth
- 移除 margin、height、color
-
> feat: refactor divider

- demo/pages/Checklist/index.axml
- demo/pages/Checklist/index.js
- src/Checklist/ChecklistItem/index.ts
- src/Checklist/ChecklistItem/props.d.ts
- src/Checklist/ChecklistItem/props.js
- src/Checklist/index.axml
- src/Checklist/index.sjs
- src/Checklist/index.ts
- src/Checklist/props.d.ts
- src/Checklist/props.js
> feat: checklist controlled

- src/Input/index.md
- src/Input/index.ts
- src/Input/props.d.ts
> fix: input onChange

- demo/pages/CheckboxGroup/index.axml
- src/Checkbox/CheckboxGroup/index.axml
- src/Checkbox/CheckboxGroup/index.ts
- src/Checklist/index.ts
- src/Selector/index.ts
> fix: fix value

- src/Badge/index.less
> fix(badge): fix style

- demo/pages/Slider/index.acss
- demo/pages/Slider/index.axml
- demo/pages/Slider/index.js
- demo/pages/Slider/index.json
- src/Slider/index.axml
- src/Slider/index.json
- src/Slider/index.less
- src/Slider/index.md
- src/Slider/index.ts
- src/Slider/props.d.ts
- src/Slider/props.js
```html
<slider defaultValue="{{80}}" /> // 非受控
<slider value="{{value}}" onChange="onChange" /> // 受控
```
> fix: slider

- demo/pages/ButtonIcon/index.axml
- demo/pages/ButtonInline/index.axml
- src/Button/index.axml
- src/Button/index.less
- src/Button/index.md
- src/Button/index.sjs
- src/Button/index.ts
- src/Button/props.d.ts
- src/Button/props.js
> fix: button

- demo/pages/Avatar/index.acss
- demo/pages/Avatar/index.axml
- demo/pages/Avatar/index.json
- src/Avatar/index.axml
- src/Avatar/index.less
- src/Avatar/index.md
- src/Avatar/index.sjs
- src/style/themes/color.less
> fix: avatar

- demo/pages/Loading/index.acss
- demo/pages/Loading/index.axml
- src/Loading/index.axml
- src/Loading/index.less
- src/Loading/index.md
- src/Loading/index.sjs
- src/Loading/props.d.ts
- src/Loading/props.js
- src/style/themes/color.less
> fix: loading

- demo/pages/Container/index.axml
- demo/pages/Container/index.json
- src/Container/index.axml
https://github.com/ant-design/ant-design-mini/issues/238
> fix: container

- demo/pages/Skeleton/index.acss
- demo/pages/Skeleton/index.axml
- demo/pages/Skeleton/index.json
- src/Skeleton/Avatar/index.axml
- src/Skeleton/Avatar/index.less
- src/Skeleton/Avatar/index.sjs
- src/Skeleton/Avatar/index.ts
- src/Skeleton/Button/index.axml
- src/Skeleton/Button/index.less
- src/Skeleton/Button/index.sjs
- src/Skeleton/Button/index.ts
- src/Skeleton/Custom/index.axml
- src/Skeleton/Custom/index.json
- src/Skeleton/Custom/index.less
- src/Skeleton/Custom/index.ts
- src/Skeleton/Paragraph/index.axml
- src/Skeleton/index.axml
- src/Skeleton/index.md
- src/Skeleton/props.d.ts
- src/Skeleton/props.js
> fix: skeleton

- src/Checkbox/index.less
- src/Radio/index.less
https://github.com/ant-design/ant-design-mini/issues/306
> fix: checkbox radiobox

- src/mixins/value.ts
> fix: mixin value

- demo/pages/CascaderPicker/index.acss
- demo/pages/CascaderPicker/index.axml
- demo/pages/CascaderPicker/index.js
- demo/pages/CascaderPicker/index.json
- demo/pages/DatePicker/index.axml
- demo/pages/DatePicker/index.json
- demo/pages/GuideTour/index.axml
- demo/pages/GuideTour/index.js
- demo/pages/Picker/index.axml
- demo/pages/Picker/index.json
- demo/pages/PopoverList/index.acss
- demo/pages/PopoverList/index.axml
- demo/pages/PopoverList/index.less
- demo/pages/TabBar/index.axml
- demo/pages/TabBar/index.js
- src/GuideTour/index.axml
- src/GuideTour/index.md
- src/Popover/index.less
* 调整Piker、DatePicker demo
* 调整Popover 边距 & demo
* 调整GuideTour demo
> 1.0 wyj new

- src/GuideTour/index.axml
- src/GuideTour/index.less
> fix: fix GuideTour button

- demo/app.json
- demo/pages/FormCustom/checklist/index.axml
- demo/pages/FormCustom/checklist/index.js
- demo/pages/FormCustom/checklist/index.json
- demo/pages/FormCustom/checklist/index.less
- demo/pages/FormCustom/checklist/index.sjs
- demo/pages/FormCustom/index.axml
- demo/pages/FormCustom/index.js
- demo/pages/FormCustom/index.json
- demo/pages/FormCustom/index.less
- demo/pages/FormCustom/location/index.axml
- demo/pages/FormCustom/location/index.js
- demo/pages/FormCustom/location/index.json
- demo/pages/FormCustom/location/index.less
- demo/pages/FormCustom/location/index.sjs
- src/Form/FormInput/index.axml
- src/Form/index.md
> feat: add form custom

- src/Collapse/index.ts
- src/Input/InputBlur/index.ts
- src/Slider/index.ts
- src/mixins/value.ts
> fix: value

- demo/pages/Form/city.js
- demo/pages/Form/index.js
- src/DatePicker/RangePicker/index.ts
- src/DatePicker/index.ts
- src/Picker/CascaderPicker/index.ts
- src/Picker/index.ts
- src/Popup/index.ts
* fix Picker、DatePicker not sync error on appx1
> fix: fix Picker、DatePicker not sync error

- config/config.ts
- docs/components/globalPC.less
> feat: 官网导航添加国内镜像&版本切换

- src/Tabs/index.ts
> fix: fix Tabs scrollLeft

- docs/guide/faq.md
- docs/guide/quick-start.md
> feat: update docs

- src/Picker/index.axml
> fix: fix Picker style

- src/Selector/index.md
> feat: 修改Selector文档

- src/Checkbox/index.less
- src/Radio/index.less
> feat: 修改Checkbox、Radio icon样式优先级

- .dumi/theme/builtins/Previewer.tsx
> fix: build

- demo/app.json
- demo/pages/SelectorFilter/index.axml
- demo/pages/SelectorFilter/index.js
- demo/pages/SelectorFilter/index.json
- demo/pages/SelectorFilter/index.less
- demo/utils/constants.js
- src/Selector/index.md
> feat: add SelectorFilter demo

- src/Picker/CascaderPicker/index.ts
> fix: fix CascaderPicker dynamic options

- demo/app.json
- demo/pages/InputSearchBar/index.axml
- demo/utils/constants.js
- src/Input/InputBlur/props.js
- src/Input/index.md
- src/Input/props.js
> fix: input

- demo/pages/PopoverList/index.axml
- demo/pages/PopoverList/index.less
- src/Popover/index.md
> fix: popover

- src/TabBar/index.md
> feat: 修改Tabbar文档

- .dumi/theme/builtins/Icon.tsx
> fix(docs): fix icon docs - clear invalid

- src/Checkbox/index.axml
> fix: checkbox

- src/Radio/index.axml
> fix: radio

- src/ImageUpload/index.md
> chore(imageUpload): 调整 ImageUpload 文档

- src/Input/index.md
> docs(input): 文档透出type属性

- src/Picker/CascaderPicker/index.axml
- src/Picker/index.axml
- src/Picker/index.md
- picker indicatorClass 统一命名为 indicatorClassName
> feat(picker): picker indicatorClass 统一命名为 indicatorClassName

- src/NoticeBar/index.md
- noticeBar 文档透出extra插槽和 icon 属性相关用法
> docs(noticeBar): 文档透出extra插槽

- src/DatePicker/RangePicker/index.axml
- src/DatePicker/index.axml
- src/DatePicker/index.md
- src/Form/FormCascaderPicker/index.axml
- src/Form/FormDatePicker/index.axml
- src/Form/FormPicker/index.axml
- src/Form/FormRangePicker/index.axml
- src/Picker/CascaderPicker/index.axml
- src/Picker/index.md
* indicatorClass 统一命名为 indicatorClassName
* 修改Picker、DatePicker文档
>  indicatorClass 统一命名为 indicatorClassName&修改Picker、DatePicker文档

- src/Input/index.md
- src/Steps/index.md
> docs: 修改文档

- docs/guide/faq.md
- docs/guide/migration-v1.md
- docs/guide/quick-start.md
> docs: 修改指南文档

- demo/pages/Modal/index.axml
- demo/pages/Modal/index.js
> feat: 修改Modal demo

- demo/pages/SwipeAction/index.less
- demo/pages/SwipeActionAnimation/index.less
- demo/pages/SwipeActionLeft/index.less
- demo/pages/SwipeActionLeftRight/index.less
- demo/pages/SwipeActionMove/index.less
- demo/pages/SwipeActionNumber/index.less
- demo/pages/SwipeActionSpeed/index.less
- demo/pages/SwipeActionTap/index.less
- demo/pages/SwipeActionWidth/index.less
- package.json
- src/_base/index.less
- 删除alipay-style依赖,修复swiperAction样式引入问题
> fix(swiperAction): 删除alipay-style依赖,修复swiperAction样式引入问题

- src/Collapse/index.md
- docs(collapse): 文档透出CollapseItem的disabled字段
> docs(collapse): 文档透出CollapseItem的disabled字段

- src/Form/FormItem/index.ts
- chore(formItem): 删除formItem无用代码
> chore(formItem): 删除formItem无用代码

- demo/pages/Container/index.axml
- src/Container/ContainerHeader/index.axml
- src/Container/ContainerHeader/index.less
- src/Container/index.axml
- src/Container/index.less
Container无title、headerRight时隐藏header #558
> feat(Container): 无title、headerRight时隐藏header

- demo/app.json
- demo/pages/CollapseWithCheckbox/index.acss
- demo/pages/CollapseWithCheckbox/index.axml
- demo/pages/CollapseWithCheckbox/index.js
- demo/pages/CollapseWithCheckbox/index.json
- demo/utils/constants.js
- src/Collapse/index.md
> docs: add collapse checkbox

- demo/app.json
- demo/pages/CheckboxCustomGroup/index.axml
- demo/pages/CheckboxCustomGroup/index.js
- demo/pages/CheckboxCustomGroup/index.json
- demo/utils/constants.js
- src/Checkbox/index.md
> docs: add CheckboxCustomGroup demo

- .dumi/theme/builtins/Previewer.tsx
> docs: fix url

- src/Container/ContainerHeader/index.axml
- src/Container/ContainerHeader/index.less
- src/Container/index.axml
- src/Container/index.less
> fix(Container): fix overflow style

- .dumi/theme/builtins/iframe.html
> feat: 模拟器新版本

- src/Tabs/index.md
> docs(tabs): 修改文档错别字

- demo/app.json
- demo/pages/FormJSON/form-json/index.axml
- demo/pages/FormJSON/form-json/index.js
- demo/pages/FormJSON/form-json/index.json
- demo/pages/FormJSON/index.axml
- demo/pages/FormJSON/index.js
- demo/pages/FormJSON/index.json
- demo/utils/constants.js
- src/Form/index.md
> docs: add form from json

- src/Steps/index.less
> fix: steps

- src/Form/FormSwitch/index.axml
- src/Switch/index.md
> fix: form-switch

- src/IndexBar/index.ts
> fix: indexbar query select

- src/IndexBar/index.md
> docs: indexbar

- demo/pages/FormValidate/index.axml
- demo/pages/FormValidate/index.js
- demo/pages/FormValidate/index.json
- src/Form/form.ts
- src/Form/index.md
> feat: form

- src/DatePicker/RangePicker/index.axml
- src/DatePicker/RangePicker/props.ts
- src/DatePicker/index.axml
- src/DatePicker/index.md
- src/DatePicker/props.ts
- src/Form/FormCascaderPicker/index.axml
- src/Form/FormDatePicker/index.axml
- src/Form/FormPicker/index.axml
- src/Form/FormRangePicker/index.axml
- src/Picker/CascaderPicker/index.axml
- src/Picker/CascaderPicker/props.ts
- src/Picker/index.axml
- src/Picker/index.md
- src/Picker/props.ts
- src/Popup/index.axml
- src/Popup/index.less
- src/Popup/index.md
- src/Popup/props.ts
> feat(Popup): add animationType

- demo/pages/TabsScroll/index.axml
- src/Tabs/index.md
- src/Tabs/index.ts
- src/Tabs/props.ts
> feat: tabs

- src/Slider/index.less
> feat(Slider): 阻止左右滑动时上下滑动

- package.json
> chore: build

- src/Picker/index.ts
> fix: Picker

- src/DatePicker/RangePicker/index.ts
> feat(RangePicker): 修改切换交互

- demo/pages/Stepper/index.axml
- demo/pages/Stepper/index.js
- src/Stepper/__tests__/index.test.ts
- src/Stepper/index.axml
- src/Stepper/index.md
- src/Stepper/index.ts
- src/Stepper/utils.ts
- tests/utils.ts
> fix: stepper

- src/Picker/index.less
> fix(Picker): fix content slot

- package.json
https://github.com/chaijs/get-func-name/issues/42
> fix:  临时锁死版本

- compiled/alipay/src/Slider/index.ts
- src/Slider/index.ts
1. 修复文案计算错误的问题
2. 修复 step 设置为 0.5 无效的问题
> fix:  修复 Slider 的 step 设置为 0.5 无效的问题

- compiled/alipay/demo/pages/DatePicker/index.axml
- compiled/alipay/demo/pages/Picker/index.axml
- compiled/alipay/src/DatePicker/RangePicker/props.ts
- compiled/alipay/src/DatePicker/index.md
- compiled/alipay/src/DatePicker/index.ts
- compiled/alipay/src/DatePicker/props.ts
- compiled/alipay/src/Picker/CascaderPicker/index.ts
- compiled/alipay/src/Picker/index.axml
- compiled/alipay/src/Picker/index.md
- compiled/alipay/src/Picker/index.ts
- demo/pages/DatePicker/index.axml
- demo/pages/Picker/index.axml
- src/DatePicker/RangePicker/props.ts
- src/DatePicker/index.md
- src/DatePicker/index.ts
- src/DatePicker/props.ts
- src/Picker/CascaderPicker/index.ts
- src/Picker/index.axml
- src/Picker/index.md
- src/Picker/index.ts
- tests/alipay/Picker/__tests__/index.test.ts
原先 Picker 组件提供了 maskClosable  参数， 默认值为 false。
但是实际上 maskClosable 参数并未生效，点击 mask 一定会关闭。
所以 maskClosable 的默认值调整为 true
> fix:  修复 maskClosable 不生效的问题

- src/Popup/index.md
- src/Popup/index.ts
- src/Popup/props.ts
- tests/alipay/Popup/index.test.ts
> feat: popup 组件新增 onAfterShow 与 onAfterClose 事件

- tests/alipay/Tabs/index.test.ts
> ci: added tabs component unit test

- compiled/alipay/src/Tabs/index.axml
- compiled/wechat/src/Tabs/index.wxml
- src/Tabs/index.axml.tsx
fix: https://github.com/ant-design/ant-design-mini/issues/1088
> fix: 修复 tabs 的样式问题

- compiled/alipay/demo/pages/DatePicker/index.axml
- compiled/alipay/demo/pages/DatePicker/index.js
- compiled/alipay/demo/pages/DatePicker/index.json
- compiled/alipay/src/DatePicker/index.axml
- compiled/alipay/src/DatePicker/index.md
- compiled/alipay/src/DatePicker/index.ts
- compiled/alipay/src/DatePicker/props.ts
- compiled/alipay/src/Picker/index.axml
- compiled/alipay/src/Picker/index.md
- compiled/wechat/demo/pages/DatePicker/index.js
- compiled/wechat/demo/pages/DatePicker/index.json
- compiled/wechat/demo/pages/DatePicker/index.wxml
- compiled/wechat/src/DatePicker/index.js
- compiled/wechat/src/DatePicker/index.md
- compiled/wechat/src/DatePicker/index.wxml
- compiled/wechat/src/DatePicker/props.js
- compiled/wechat/src/Picker/index.md
- compiled/wechat/src/Picker/index.wxml
- demo/pages/DatePicker/index.axml.tsx
- demo/pages/DatePicker/index.json5
- demo/pages/DatePicker/index.ts
- src/DatePicker/index.axml.tsx
- src/DatePicker/index.md
- src/DatePicker/index.ts
- src/DatePicker/props.ts
- src/Picker/index.axml.tsx
- src/Picker/index.md
https://github.com/ant-design/ant-design-mini/issues/1142
> DatePicker支持visible和defaultVisible

- tests/alipay/DatePicker/RangePicker/index.test.ts
- tests/alipay/DatePicker/RangePicker/utils.ts
- tests/alipay/Picker/CascaderPicker/__tests__/index.test.ts
- tests/alipay/Picker/CascaderPicker/__tests__/utils.ts
补充DateRangePicker和CascaderPicker的单元测试
> feat: DateRangePicker和CascaderPicker增加visible和defaultVisible后完善单元测试

- src/Dialog/props.ts
- src/PopoverList/props.ts
- src/SafeArea/props.ts
- src/SelectContact/props.ts
- src/Sticky/props.ts
- src/Table/props.ts
- src/Voucher/props.ts
如题，主要是修复 props 文件中组件 interface 命名问题
> fix: 修复部分组件 props 命名规范问题
