docs/index.md
首页使用全宽模式，去掉页面左右内边距及底部链接（红框范围）：
=> docs: enable full mode for homepage

package.json, scripts/compile.js
用户在开发钉钉小程序时，使用 antd-mini 遇见 [babel 报错](https://github.com/facebook/regenerator/issues/373)。
现改为 tsc 编译以绕过此问题。
=> fix(compile): replace babel with tsc

src/Form/FormItem/index.ts, src/Picker/index.ts, src/mixins/form.ts, src/mixins/htmlType.ts
`this.$page.data` is unavaliable when public component of one plugin is embedded in other page.
This resolution is not the final one yet.
The mechanism which share global context by `this.$page` is not solid for multiple form instance.
=> fix(Form): fix Form in plugin mode

src/Modal/index.md
=> docs(modal): fix typo and markdown table

src/VTabs/index.axml, src/VTabs/index.ts
- 修复 VTabs tab 过长，点击最后几个 tab 会自动切换到之前的 tab
- 修复 VTabs tab active时，上一个 tab 无 border-radius 样式
- https://github.com/ant-design/ant-design-mini/issues/92
=> fix(vTabs): fix click bottom tap jump to the tap before

src/CheckboxGroup/props.js
=> fix(CheckboxGroup): remove default value prop

src/CheckboxGroup/CheckboxItem/index.axml, src/CheckboxGroup/CheckboxItem/props.d.ts, src/CheckboxGroup/CheckboxItem/props.js, src/CheckboxGroup/index.axml, src/CheckboxGroup/index.json
- checkboxItem 的遍历数组如果先为 []，后变成非空数组就会导致 onchange 失效
=> fix(checkbox-group): onchange does not trigger

src/Form/FormGroup/index.axml, src/Form/FormGroup/index.less
=> fix: fix FormGroup radius props

src/Container/index.axml
=> 修复不设置标题时，标题行占位的问题

demo/pages/BladeView/index.axml, demo/pages/BladeView/index.js, src/BladeView/index.axml, src/BladeView/index.less
- bladeView sticky z-index fix
- baldeView value key fix
=> fix(bladeView): fix sticky style and value name

demo/pages/VideoUpload/index.axml, demo/pages/VideoUpload/index.js, src/VideoUpload/index.axml, src/VideoUpload/index.md, src/VideoUpload/index.ts, src/VideoUpload/props.d.ts
- 视频上传组件支持不同类型的值，包括 string 、string[] 和 File[]
- 视频上传组件不在依赖外部手动传入id，改为 this.$page.$id + this.$id  作为唯一标识
- 更新对应demo
=> feat(videoUpload): support different value type

src/ImageUpload/index.ts, src/_util/promisify.ts
修复 https://github.com/ant-design/ant-design-mini/issues/251
- 兼容钉钉小程序appx1.x下 chooseImage 返回值的差异性
appx1.x钉钉下chooseImage的结果
appx2.x支付宝chooseImage的结果
=> feat: Compatible dingding appx1.x 

demo/pages/Selector/index.acss, demo/pages/Selector/index.axml, demo/pages/Selector/index.js, demo/pages/Selector/index.json, src/Selector/index.axml, src/Selector/index.less, src/Selector/index.md, src/Selector/variable.less, src/style/themes/color.less
- 支持暗黑模式
- 新增style、activeItemStyle
- 升级对应文档
- 去掉标题区域，包括 title、desc 字段
=> feat(selector): refactor selector

src/Loading/index.axml, src/Loading/index.sjs
为方便dsl转换微信小程序做一些语法小调整：
1.微信不支持sjs解构语法，改为普通写法；
2.xml内联style的src()内带上引号，不然微信识别会有问题；
=> feat: loading组件兼容dsl转微信小程序

src/Checkbox/CheckboxGroup/index.axml, src/Checkbox/CheckboxGroup/index.less, src/Form/FormCheckboxGroup/index.axml, src/Form/FormRadioGroup/index.axml, src/Radio/RadioGroup/index.axml, src/Radio/RadioGroup/index.less
appx2下slot传递两层会导致自定义slot和slot 默认内容渲染两次，此处使用css判断的方式隐藏掉自定义slot时默认内容节点。
用于FormCheckboxGroup、FormRadioGroup label slot
=> fix: fix FormCheckboxGroup、FormRadioGroup label slot

.github/workflows/pull_request.yml, .github/workflows/pull_request_release_next.yml, .github/workflows/real_release.yml, .github/workflows/release.yml, .github/workflows/release_candidate.yml, scripts/build.js, scripts/dev.js
=> chore: build

demo/pages/Input/index.axml, src/Input/InputBlur/props.ts, src/Input/Textarea/props.ts, src/Input/index.md, src/Input/props.ts, src/mixins/value.ts
=> feat: input controlled

demo/pages/DatePicker/index.axml, demo/pages/DatePicker/index.js, src/DatePicker/RangePicker/index.ts, src/DatePicker/RangePicker/props.ts, src/DatePicker/index.md, src/DatePicker/index.ts, src/DatePicker/props.ts, src/DatePicker/util.ts, src/Form/FormDatePicker/index.axml, src/Form/FormDatePicker/index.ts, src/Form/FormRangePicker/index.axml, src/Form/FormRangePicker/index.ts
=> feat(DatePicker): add onFormatLabel

src/Picker/CascaderPicker/__tests__/index.test.ts, src/Picker/__tests__/index.test.ts, tests/utils.ts
=> ci: add Picker、CascaderPicker test

src/Stepper/index.ts
=> fix: stepper

src/Slider/index.axml
=> fix: slider

src/Button/index.axml, src/Button/props.ts
=> fix: button

src/Form/FormTextarea/props.ts
`src/Form/FormTextarea/index.ts` needs `FormTextareaDefaultProps`
```javascript
import { FormTextareaDefaultProps } from './props';
Component({
props: FormTextareaDefaultProps,
...  
});
```
=> fix: missing FormTextareaDefaultProps

src/DatePicker/RangePicker/index.ts, src/DatePicker/index.ts
修复不传值时打开时间选择默认定位项边界问题，默认定位当前时间，当前时间不在范围内定位最小值
=> fix: DatePicker

src/Form/index.md
createform 并不是 'antd-mini/es/Form/form' 导出的方法。
=> fix: 修复 form 表单 createForm Api 误写问题

src/Empty/index.axml, src/Empty/index.less, src/Empty/index.ts, src/_util/__tests__/compareVersion.spec.ts, src/_util/compareVersion.ts, src/_util/console.ts
修复 https://github.com/ant-design/ant-design-mini/issues/807
不能使用 `image` selector
=> fix: should not use element selector

src/Picker/index.less
Raise the layer of picker mask to accelerate the rendering of the mask on IOS
=> fix: raise the layer of picker mask to a compositing layer

compiled/alipay/demo/pages/Stepper/index.axml, compiled/alipay/src/Stepper/index.axml, compiled/alipay/src/Stepper/index.md, compiled/alipay/src/Stepper/props.ts, compiled/wechat/demo/pages/Stepper/index.wxml, compiled/wechat/src/Stepper/index.md, compiled/wechat/src/Stepper/index.wxml, demo/pages/Stepper/index.axml.tsx, src/Stepper/index.axml.tsx, src/Stepper/index.md, src/Stepper/props.ts
stepper 组件增加 inputReadOnly 属性实现输入框只读状态
demo 及 md 已更新
用于支持此 [issue](https://github.com/ant-design/ant-design-mini/issues/1036)
=> feat: stepper 组件增加只读属性 (#1036)

compiled/alipay/src/Avatar/index.axml, compiled/alipay/src/Avatar/props.ts, compiled/wechat/src/Avatar/index.wxml, compiled/wechat/src/Avatar/props.js, src/Avatar/index.axml.tsx, src/Avatar/props.ts
原行为：
- src 外部传入非 `undefined` 值，不显示
- src 不传入，显示默认占位
改坏之后：
- src 不传入，默认 Avatar 不显示（微信）
新行为：
- src 外部传入任意值（包括 Falsy），均显示
- src 不传入，显示默认占位
=> fix: Avatar/不再消失

compiled/alipay/src/Tabs/index.ts, compiled/wechat/src/Tabs/index.js, src/Tabs/index.ts
在 useEffect ( onInit ) 生命周期调用 updateScroll 的话，有时候会出现元素找不到的情况。
=> fix: 修改 updateScroll 调用时机

compiled/alipay/demo/pages/List/index.axml, compiled/alipay/demo/pages/List/index.js, compiled/alipay/src/List/ListItem/index.ts, compiled/alipay/src/_util/simply.ts, compiled/wechat/demo/pages/List/index.js, compiled/wechat/demo/pages/List/index.wxml, compiled/wechat/src/List/ListItem/index.js, compiled/wechat/src/_util/simply.js, demo/pages/List/index.axml.tsx, demo/pages/List/index.ts, src/List/ListItem/index.ts, src/_util/simply.ts, tests/alipay/List/__tests__/snapshot/list_item_alipay_config.txt
=> feat: listitem组件写法优化

compiled/alipay/demo/pages/Calendar/index.axml, compiled/alipay/demo/pages/Calendar/index.js, compiled/alipay/src/Calendar/index.axml, compiled/alipay/src/Calendar/index.md, compiled/alipay/src/Calendar/index.ts, compiled/alipay/src/Calendar/props.ts, compiled/alipay/src/Calendar/utils.ts, compiled/wechat/demo/pages/Calendar/index.js, compiled/wechat/demo/pages/Calendar/index.wxml, compiled/wechat/src/Calendar/index.js, compiled/wechat/src/Calendar/index.md, compiled/wechat/src/Calendar/index.wxml, compiled/wechat/src/Calendar/utils.js, demo/pages/Calendar/index.axml.tsx, demo/pages/Calendar/index.ts, src/Calendar/index.axml.tsx, src/Calendar/index.md, src/Calendar/index.ts, src/Calendar/props.ts, src/Calendar/utils.ts, tests/alipay/Calendar/__tests__/calendar.spec.ts, tests/alipay/Calendar/__tests__/snapshot/alipay_config_props.txt, tests/alipay/Calendar/__tests__/utils.spec.ts
https://ant-design-mini.antgroup.com/components/calendar  这个 calendar 组件似乎没有滑动到指定日期的 API，这个有计划支持吗？
比如日历渲染的日期是 1.1 - 12.31，日历组件选中的值是 5.1，需要在打开这个日历组件时，就自动滑动到选中的日期上
而不是每次打开这个组件的时候，都需要从头开始滑动
=> feat: 优化calendar组件选中交互，日期滚动到可视区域内

compiled/alipay/src/DatePicker/index.ts, compiled/wechat/src/DatePicker/index.js, src/DatePicker/index.ts
fix https://github.com/ant-design/ant-design-mini/issues/1149
=> fix: 修复DatePicker组件onVisibleChange事件参数未适配微信的问题

compiled/alipay/src/DatePicker/RangePicker/index.ts, compiled/alipay/src/Picker/CascaderPicker/index.ts, compiled/wechat/src/DatePicker/RangePicker/index.js, compiled/wechat/src/Picker/CascaderPicker/index.js, src/DatePicker/RangePicker/index.ts, src/Picker/CascaderPicker/index.ts
修复RangePicker和CascaderPicker组件与DatePicker相同的问题，https://github.com/ant-design/ant-design-mini/issues/1149
=> fix: [#1149]修复RangePicker和CascaderPicker组件onVisibleChange事件参数未适配微信的问题

tests/alipay/DatePicker/index.test.ts, tests/alipay/DatePicker/utils.ts
单独抽离了callVisibleChange，调用onVisibleChange方法后，sleep延长为100ms
=> feat: DatePicker增加visible和defaultVisible后完善单元测试

docs/guide/faq.en.md, docs/guide/faq.md
迁移文档的链接指的是本地主机而不是文档域。
The link to the migration document refers to the localhost instead of the documentation domain.
=> Update the link to the correct migration documentation
